export enum PoDocumentType {
  CUSTOMER_PO_COPY = 'CUSTOMER_PO_COPY',
  CUSTOMER_TECHNICAL_SPECIFICATION = 'CUSTOMER_TECHNICAL_SPECIFICATION',
  COMMERCIAL_REFERENCE = 'COMMERCIAL_REFERENCE',
  PO_DRAWING = 'PO_DRAWING',
  PO_SUPPORTING_REFERENCE = 'PO_SUPPORTING_REFERENCE',
}
