export enum RmDocumentType {
  CUSTOMER_DRAWING = 'CUSTOMER_DRAWING',
  DESIGN_DRAWING = 'DESIGN_DRAWING',
  RM_SPECIFICATION = 'RM_SPECIFICATION',
  TECHNICAL_DRAWING = 'TECHNICAL_DRAWING',
  DESIGNER_REFERENCE = 'DESIGNER_REFERENCE',
}
