export enum ScDocumentType {
  SC_DRAWING = 'SC_DRAWING',
  CUSTOMER_REFERENCE = 'CUSTOMER_REFERENCE',
  SC_SUPPORTING_REFERENCE = 'SC_SUPPORTING_REFERENCE',
  TECHNICAL_REFERENCE = 'TECHNICAL_REFERENCE',
}
