export enum NotificationType {
  RM_SUBMITTED = 'RM_SUBMITTED',
  MATERIAL_ISSUED = 'MATERIAL_ISSUED',
  ADDITIONAL_MATERIAL_REQUESTED = 'ADDITIONAL_MATERIAL_REQUESTED',
  ADDITIONAL_REQUEST = 'ADDITIONAL_REQUEST', // Backward compatibility for existing Phase 15 event name
  SC_COMPLETED = 'SC_COMPLETED',
  INFO = 'INFO',
  SECURITY = 'SECURITY',
  WORKFLOW = 'WORKFLOW',
  SYSTEM = 'SYSTEM',
  // Phase 19.8 — Delivery Challan events
  DC_CREATED = 'DC_CREATED',
  DC_DISPATCHED = 'DC_DISPATCHED',
  DC_APPROACHING_SLA = 'DC_APPROACHING_SLA',
  DC_OVERDUE = 'DC_OVERDUE',
  DC_PARTIALLY_RETURNED = 'DC_PARTIALLY_RETURNED',
  DC_RETURNED = 'DC_RETURNED',
  DC_CLOSED = 'DC_CLOSED',
}
