export enum NotificationTargetEntity {
  RM_REQUEST = 'RM_REQUEST',
  MATERIAL_ISSUE = 'MATERIAL_ISSUE',
  ADDITIONAL_MATERIAL_REQUEST = 'ADDITIONAL_MATERIAL_REQUEST',
  ADDITIONAL_REQUEST = 'ADDITIONAL_REQUEST',
  SC = 'SC',
}
