export enum NotificationType {
  RM_SUBMITTED = 'RM_SUBMITTED',
  MATERIAL_ISSUED = 'MATERIAL_ISSUED',
  ADDITIONAL_MATERIAL_REQUESTED = 'ADDITIONAL_MATERIAL_REQUESTED',
  ADDITIONAL_REQUEST = 'ADDITIONAL_REQUEST', // Backward compatibility for existing Phase 15 event name
  SC_COMPLETED = 'SC_COMPLETED',
  INFO = 'INFO',
  SECURITY = 'SECURITY',
  WORKFLOW = 'WORKFLOW',
  SYSTEM = 'SYSTEM',
}
