export const ROLES = {
  ADMIN: 'ADMIN',
  DESIGN_USER: 'DESIGN_USER',
  SENIOR_MANAGER: 'SENIOR_MANAGER',
  STORES_MANAGER: 'STORES_MANAGER',
  PRODUCTION_USER: 'PRODUCTION_USER',
  ACCOUNTS: 'ACCOUNTS',
  PRODUCTION_MANAGER: 'PRODUCTION_MANAGER',
  MANAGEMENT: 'MANAGEMENT',
} as const;

export const WORKFLOW_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  SENIOR_VERIFIED: 'SENIOR_VERIFIED',
  STORES_PENDING: 'STORES_PENDING',
  PARTIALLY_ISSUED: 'PARTIALLY_ISSUED',
  ISSUED: 'ISSUED',
  RECEIVED: 'RECEIVED',
  IN_PRODUCTION: 'IN_PRODUCTION',
  ADDITIONAL_REQUEST: 'ADDITIONAL_REQUEST',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
} as const;

export const SYSTEM_EVENTS = {
  RM_SUBMITTED: 'rm.submitted',
  RM_VERIFIED: 'rm.verified',
  RM_REJECTED: 'rm.rejected',
  MATERIAL_ISSUED: 'material.issued',
  MATERIAL_RECEIVED: 'material.received',
  MATERIAL_CONSUMED: 'material.consumed',
  MATERIAL_RETURNED: 'material.returned',
  ADDITIONAL_REQUESTED: 'additional.requested',
  SC_COMPLETED: 'sc.completed',
} as const;
