export const ROLES = {
  ADMIN: 'ADMIN',
  DESIGNER: 'DESIGNER',
  STORES: 'STORES',
  PRODUCTION: 'PRODUCTION',
  SENIOR_MANAGER: 'SENIOR_MANAGER',
  GENERAL_MANAGER: 'GENERAL_MANAGER',
} as const;

export const WORKFLOW_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  STORES_PENDING: 'STORES_PENDING',
  PARTIALLY_ISSUED: 'PARTIALLY_ISSUED',
  ISSUED: 'ISSUED',
  RECEIVED: 'RECEIVED',
  IN_PRODUCTION: 'IN_PRODUCTION',
  ADDITIONAL_REQUEST: 'ADDITIONAL_REQUEST',
  COMPLETED: 'COMPLETED',
} as const;

export const SYSTEM_EVENTS = {
  RM_SUBMITTED: 'rm.submitted',
  MATERIAL_ISSUED: 'material.issued',
  MATERIAL_RECEIVED: 'material.received',
  MATERIAL_CONSUMED: 'material.consumed',
  MATERIAL_RETURNED: 'material.returned',
  ADDITIONAL_REQUESTED: 'additional.requested',
  SC_COMPLETED: 'sc.completed',
} as const;
