export enum UserRole {
  // Core Operational Roles
  ADMIN = 'ADMIN',
  DESIGN_USER = 'DESIGN_USER',
  SENIOR_MANAGER = 'SENIOR_MANAGER',
  STORES_MANAGER = 'STORES_MANAGER',
  PRODUCTION_USER = 'PRODUCTION_USER',

  // Extended / Future Governance Roles
  ACCOUNTS = 'ACCOUNTS',
  PRODUCTION_MANAGER = 'PRODUCTION_MANAGER',
  MANAGEMENT = 'MANAGEMENT',
}
