export enum ProductionDocumentType {
  PRODUCTION_DRAWING = 'PRODUCTION_DRAWING',
  MACHINING_INSTRUCTION = 'MACHINING_INSTRUCTION',
  PRODUCTION_SUPPORTING_RECORD = 'PRODUCTION_SUPPORTING_RECORD',
  EXECUTION_EVIDENCE = 'EXECUTION_EVIDENCE',
  PRODUCTION_REFERENCE = 'PRODUCTION_REFERENCE',
}
